apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot
secrets:
- name: nightly-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-minimal
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["tekton-triggers"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robot-release-minimal
subjects:
- kind: ServiceAccount
  name: robot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-minimal
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-cluster-minimal
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: robot-release-cluster-minimal
subjects:
- kind: ServiceAccount
  name: robot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-cluster-minimal
