# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: configmap-deploy-failed-slack
spec:
  params:
  - name: taskRunName
    description: The name of the TaskRun
  - name: taskRunNamespace
    description: The namespace of the TaskRun
  - name: dashboardBaseURL
    description: The base URL of the Tekton dashboard
  - name: gitResource
    description: The git sha of the deployed resource
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      name: send-to-webhook-slack-$(uid)
    spec:
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: robocat-slack-app-webhook
        - name: message
          value: >-
            :boom: The TaskRun <$(tt.params.dashboardBaseURL)/#/namespaces/$(tt.params.taskRunNamespace)/taskruns/$(tt.params.taskRunName)|$(tt.params.taskRunNamespace)/$(tt.params.taskRunName)>
            failed to deploy <$(tt.params.dashboardBaseURL)/#/namespaces/$(tt.params.taskRunNamespace)/pipelineresources/$(tt.params.gitResource)|$(tt.params.taskRunNamespace)/$(tt.params.gitResource)>